"""initial schema

Revision ID: 5eedff8c7f20
Revises: 
Create Date: 2026-02-10 19:49:55.745816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eedff8c7f20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_bots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_token_encrypted', sa.Text(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_username', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id'),
    sa.UniqueConstraint('bot_token_encrypted')
    )
    with op.batch_alter_table('sub_bots', schema=None) as batch_op:
        batch_op.create_index('idx_sub_bots_bot_id', ['bot_id'], unique=True)
        batch_op.create_index('idx_sub_bots_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('idx_sub_bots_status', ['status'], unique=False)

    op.create_table('ad_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ad_text', sa.Text(), nullable=False),
    sa.Column('ad_url', sa.String(length=512), nullable=True),
    sa.Column('button_text', sa.String(length=64), nullable=True),
    sa.Column('button_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_bot_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('impression_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_bot_id'], ['sub_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_configs', schema=None) as batch_op:
        batch_op.create_index('idx_ad_active_priority', ['is_active', 'priority'], unique=False)
        batch_op.create_index('idx_ad_target', ['target_type', 'target_bot_id'], unique=False)

    op.create_table('bot_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_bot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_banned_by_telegram', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sub_bot_id'], ['sub_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_users', schema=None) as batch_op:
        batch_op.create_index('idx_bot_users_sub_bot_blocked', ['sub_bot_id', 'is_blocked'], unique=False)
        batch_op.create_index('idx_bot_users_sub_bot_user', ['sub_bot_id', 'user_id'], unique=True)

    op.create_table('broadcast_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_bot_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_file_id', sa.String(length=256), nullable=True),
    sa.Column('content_caption', sa.Text(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sub_bot_id'], ['sub_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broadcast_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_broadcast_status', ['status'], unique=False)
        batch_op.create_index('idx_broadcast_sub_bot', ['sub_bot_id', 'status'], unique=False)

    op.create_table('message_maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_bot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_msg_id', sa.Integer(), nullable=False),
    sa.Column('forwarded_msg_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sub_bot_id'], ['sub_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_maps', schema=None) as batch_op:
        batch_op.create_index('idx_msg_map_created', ['created_at'], unique=False)
        batch_op.create_index('idx_msg_map_forwarded', ['sub_bot_id', 'forwarded_msg_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_maps', schema=None) as batch_op:
        batch_op.drop_index('idx_msg_map_forwarded')
        batch_op.drop_index('idx_msg_map_created')

    op.drop_table('message_maps')
    with op.batch_alter_table('broadcast_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_broadcast_sub_bot')
        batch_op.drop_index('idx_broadcast_status')

    op.drop_table('broadcast_tasks')
    with op.batch_alter_table('bot_users', schema=None) as batch_op:
        batch_op.drop_index('idx_bot_users_sub_bot_user')
        batch_op.drop_index('idx_bot_users_sub_bot_blocked')

    op.drop_table('bot_users')
    with op.batch_alter_table('ad_configs', schema=None) as batch_op:
        batch_op.drop_index('idx_ad_target')
        batch_op.drop_index('idx_ad_active_priority')

    op.drop_table('ad_configs')
    with op.batch_alter_table('sub_bots', schema=None) as batch_op:
        batch_op.drop_index('idx_sub_bots_status')
        batch_op.drop_index('idx_sub_bots_owner_id')
        batch_op.drop_index('idx_sub_bots_bot_id')

    op.drop_table('sub_bots')
    # ### end Alembic commands ###
